### ISSUE TITLE
Local transformer names must exist and be unique (PassThrough). Read from based on mimetype list

### ISSUE THREAD

**Issue by good-22** [Alfresco/acs-community-deployment#122]
Hello, I install acs by k8s, and got the ERROR "Local transformer names must exist and be unique (PassThrough). Read from based on mimetype list" , How can I do? Thanks!

2020-07-30 04:07:36,694  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Startup of 'Synchronization' subsystem, ID: [Synchronization, default] complete
2020-07-30 04:07:36,703  INFO  [service.descriptor.DescriptorService] [localhost-startStop-1] Alfresco JVM - v11.0.7+10; maximum heap size 1450.000MB
2020-07-30 04:07:36,704  INFO  [service.descriptor.DescriptorService] [localhost-startStop-1] Server Mode :UNKNOWN
2020-07-30 04:07:36,707  INFO  [service.descriptor.DescriptorService] [localhost-startStop-1] Alfresco Content Services started (Community). Current version: 6.2.1 (r531c5430-b1572) schema 13,001. Originally installed version: 6.2.1 (r531c5430-b1572) schema 13,001.
2020-07-30 04:07:36,785  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Starting 'ActivitiesFeed' subsystem, ID: [ActivitiesFeed, default]
2020-07-30 04:07:37,689  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Startup of 'ActivitiesFeed' subsystem, ID: [ActivitiesFeed, default] complete
2020-07-30 04:07:37,689  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Starting 'Replication' subsystem, ID: [Replication, default]
2020-07-30 04:07:37,700  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Startup of 'Replication' subsystem, ID: [Replication, default] complete
2020-07-30 04:07:41,299  INFO  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Starting 'Messaging' subsystem, ID: [Messaging, default]
2020-07-30 04:08:05,047  ERROR [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-1] Local transformer names must exist and be unique (PassThrough). Read from based on mimetype list
2020-07-30 04:10:00,785  ERROR [quartz.core.JobRunShell] [SearchScheduler_Worker-1] Job Solr.SolrWatcher threw an unhandled Exception: 
org.alfresco.error.AlfrescoRuntimeException: 06300067 The host did not accept the connection within timeout of 500 ms
	at org.alfresco.repo.search.impl.solr.AbstractSolrAdminHTTPClient.getOperation(AbstractSolrAdminHTTPClient.java:96)
	at org.alfresco.repo.solr.SOLRAdminClient.executeAction(SOLRAdminClient.java:221)
	at org.alfresco.repo.solr.SOLRAdminClient$SolrTracker.pingSolr(SOLRAdminClient.java:333)
	at org.alfresco.repo.solr.SOLRWatcherJob.execute(SOLRWatcherJob.java:54)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 500 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:155)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

**Comment by good-22** [comment]
[root@172-16-0-101 acs-community-deployment]# cat deployment-alfresco.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco
  namespace: acs-community
  labels:
    app: alfresco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco
  template:
    metadata:
      labels:
        app: alfresco
    spec:
      containers:
        - image: alfresco/alfresco-content-repository-community:6.2.1-A8
          imagePullPolicy: IfNotPresent
          name: alfresco
          resources:
            limits:
              memory: 1Gi
              cpu: '0.5'
            requests:
              memory: 0.2Gi
              cpu: '0.1'
          env:
            - name: JAVA_OPTS
              value: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6-ser
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=share
                -Dshare.port=8080
                -Dalfresco.host=alfresco
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://alfresco:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq-ser:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=HELM_CHART
                -DlocalTransform.core-aio.url=http://transform-core-aio-ser:8090/
                -Dalfresco-pdf-renderer.url=http://transform-core-aio-ser:8090/
                -Djodconverter.url=http://transform-core-aio-ser:8090/
                -Dimg.url=http://transform-core-aio-ser:8090/
                -Dtika.url=http://transform-core-aio-ser:8090/
                -Dtransform.misc.url=http://transform-core-aio-ser:8090/
                -Dcsrf.filter.enabled=false
                -Xms1500m -Xmx1500m
                "
---
apiVersion: v1
kind: Service
metadata:
  name: alfresco
  labels:
    app: alfresco
  namespace: acs-community
spec:
  ports:
    - port: 8080
      name: alfresco
      targetPort: 8080
  selector:
    pod: alfresco

**Comment by gavincornwell** [comment]
Firstly, thank you for raising this issue and apologies for the time it's taken to respond.

As you may have seen from the recent blog post (https://hub.alfresco.com/t5/alfresco-content-services-blog/acs-community-repositories-consolidation/ba-p/302770) we have been consolidating the deployment repositories and this one is being archived.

We have also changed the way we deploy previous versions of the product including Community. Please refer to the new Helm documentation (https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/README.md). If the problem still exists please raise a new issue in https://github.com/Alfresco/acs-deployment.
